### ISSUE TITLE
build issue using Java 13 Java 21 

### ISSUE THREAD

**Issue by systems1** [jonatan-ivanov/teahouse#10]
what are environment requirements for build to work 
tried with Java 13 Java 21 
./gradlew bootJar
BUILD FAILED
https://scans.gradle.com/s/b3ovwpnh55ffe

**Comment by jonatan-ivanov** [comment]
Have you checked the `build.gradle` file?
https://github.com/jonatan-ivanov/teahouse/blob/2645b123a478717c7777e273767bfe10950552ba/build.gradle#L70

Also, Java 13 is very old and not supported anymore.

**Comment by systems1** [comment]
Used Java 21 build failed then tried Java 13
Heres Java 21 output 
>java -version
openjdk version "21.0.1" 2023-10-17
OpenJDK Runtime Environment (build 21.0.1+12-29)
OpenJDK 64-Bit Server VM (build 21.0.1+12-29, mixed mode, sharing)

./gradlew bootRun
Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'teahouse'.
> Could not resolve all files for configuration ':classpath'.
   > Did not resolve 'org.apache.httpcomponents.core5:httpcore5:5.2' which is part of the dependency lock state
   > Did not resolve 'org.antlr:antlr4-runtime:4.7.2' which is part of the dependency lock state
   > Did not resolve 'org.springframework:spring-jcl:6.0.10' which is part of the dependency lock state
   > Did not resolve 'org.apache.httpcomponents.client5:httpclient5:5.2.1' which is part of the dependency lock state
   > Did not resolve 'org.springframework.boot:spring-boot-buildpack-platform:3.2.0' which is part of the dependency lock state
   > Did not resolve 'org.springframework.boot:spring-boot-loader-tools:3.2.0' which is part of the dependency lock state
   > Did not resolve 'com.fasterxml.jackson.core:jackson-core:2.14.2' which is part of the dependency lock state
   > Did not resolve 'com.fasterxml.jackson.core:jackson-databind:2.14.2' which is part of the dependency lock state
   > Did not resolve 'org.springframework:spring-core:6.0.10' which is part of the dependency lock state
   > Did not resolve 'com.google.code.findbugs:jsr305:3.0.2' which is part of the dependency lock state
   > Did not resolve 'io.spring.gradle:dependency-management-plugin:1.1.4' which is part of the dependency lock state
   > Did not resolve 'net.java.dev.jna:jna:5.13.0' which is part of the dependency lock state
   > Did not resolve 'com.fasterxml.jackson.core:jackson-annotations:2.14.2' which is part of the dependency lock state
   > Did not resolve 'org.apache.httpcomponents.core5:httpcore5-h2:5.2' which is part of the dependency lock state
   > Did not resolve 'org.apache.commons:commons-compress:1.23.0' which is part of the dependency lock state
   > Did not resolve 'com.fasterxml.jackson:jackson-bom:2.14.2' which is part of the dependency lock state
   > Did not resolve 'net.java.dev.jna:jna-platform:5.13.0' which is part of the dependency lock state
   > Did not resolve 'org.tomlj:tomlj:1.0.0' which is part of the dependency lock state
   > Did not resolve 'org.springframework.boot:spring-boot-gradle-plugin:3.2.0' which is part of the dependency lock state
   > Did not resolve 'com.fasterxml.jackson.module:jackson-module-parameter-names:2.14.2' which is part of the dependency lock state
   > Could not resolve org.springframework.boot:spring-boot-gradle-plugin:3.+.
     Required by:
         project :
      > No matching variant of org.springframework.boot:spring-boot-gradle-plugin:3.2.0 was found. The consumer was configured to find a library for use during runtime, compatible with Java 13, packaged as a jar, and its dependencies declared externally, as well as attribute 'org.gradle.plugin.api-version' with value '8.4' but:
          - Variant 'apiElements' capability org.springframework.boot:spring-boot-gradle-plugin:3.2.0 declares a library, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component for use during compile-time, compatible with Java 17 and the consumer needed a component for use during runtime, compatible with Java 13
              - Other compatible attribute:
                  - Doesn't say anything about org.gradle.plugin.api-version (required '8.4')
          - Variant 'javadocElements' capability org.springframework.boot:spring-boot-gradle-plugin:3.2.0 declares a component for use during runtime, and its dependencies declared externally:
              - Incompatible because this component declares documentation and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about its target Java version (required compatibility with Java 13)
                  - Doesn't say anything about its elements (required them packaged as a jar)
                  - Doesn't say anything about org.gradle.plugin.api-version (required '8.4')
          - Variant 'mavenOptionalApiElements' capability org.springframework.boot:spring-boot-gradle-plugin-maven-optional:3.2.0 declares a library, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component for use during compile-time, compatible with Java 17 and the consumer needed a component for use during runtime, compatible with Java 13
              - Other compatible attribute:
                  - Doesn't say anything about org.gradle.plugin.api-version (required '8.4')
          - Variant 'mavenOptionalRuntimeElements' capability org.springframework.boot:spring-boot-gradle-plugin-maven-optional:3.2.0 declares a library for use during runtime, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component, compatible with Java 17 and the consumer needed a component, compatible with Java 13
              - Other compatible attribute:
                  - Doesn't say anything about org.gradle.plugin.api-version (required '8.4')
          - Variant 'runtimeElements' capability org.springframework.boot:spring-boot-gradle-plugin:3.2.0 declares a library for use during runtime, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component, compatible with Java 17 and the consumer needed a component, compatible with Java 13
              - Other compatible attribute:
                  - Doesn't say anything about org.gradle.plugin.api-version (required '8.4')
          - Variant 'sourcesElements' capability org.springframework.boot:spring-boot-gradle-plugin:3.2.0 declares a component for use during runtime, and its dependencies declared externally:
              - Incompatible because this component declares documentation and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about its target Java version (required compatibility with Java 13)
                  - Doesn't say anything about its elements (required them packaged as a jar)
                  - Doesn't say anything about org.gradle.plugin.api-version (required '8.4')
   > Could not resolve org.springframework.boot:spring-boot-gradle-plugin:3.+.
     Required by:
         project :
      > No matching variant of org.springframework.boot:spring-boot-gradle-plugin:3.2.0 was found. The consumer was configured to find a library for use during runtime, compatible with Java 13, packaged as a jar, and its dependencies declared externally, as well as attribute 'org.gradle.plugin.api-version' with value '8.4' but:
          - Variant 'apiElements' capability org.springframework.boot:spring-boot-gradle-plugin:3.2.0 declares a library, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component for use during compile-time, compatible with Java 17 and the consumer needed a component for use during runtime, compatible with Java 13
              - Other compatible attribute:
                  - Doesn't say anything about org.gradle.plugin.api-version (required '8.4')
          - Variant 'javadocElements' capability org.springframework.boot:spring-boot-gradle-plugin:3.2.0 declares a component for use during runtime, and its dependencies declared externally:
              - Incompatible because this component declares documentation and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about its target Java version (required compatibility with Java 13)
                  - Doesn't say anything about its elements (required them packaged as a jar)
                  - Doesn't say anything about org.gradle.plugin.api-version (required '8.4')
          - Variant 'mavenOptionalApiElements' capability org.springframework.boot:spring-boot-gradle-plugin-maven-optional:3.2.0 declares a library, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component for use during compile-time, compatible with Java 17 and the consumer needed a component for use during runtime, compatible with Java 13
              - Other compatible attribute:
                  - Doesn't say anything about org.gradle.plugin.api-version (required '8.4')
          - Variant 'mavenOptionalRuntimeElements' capability org.springframework.boot:spring-boot-gradle-plugin-maven-optional:3.2.0 declares a library for use during runtime, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component, compatible with Java 17 and the consumer needed a component, compatible with Java 13
              - Other compatible attribute:
                  - Doesn't say anything about org.gradle.plugin.api-version (required '8.4')
          - Variant 'runtimeElements' capability org.springframework.boot:spring-boot-gradle-plugin:3.2.0 declares a library for use during runtime, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component, compatible with Java 17 and the consumer needed a component, compatible with Java 13
              - Other compatible attribute:
                  - Doesn't say anything about org.gradle.plugin.api-version (required '8.4')
          - Variant 'sourcesElements' capability org.springframework.boot:spring-boot-gradle-plugin:3.2.0 declares a component for use during runtime, and its dependencies declared externally:
              - Incompatible because this component declares documentation and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about its target Java version (required compatibility with Java 13)
                  - Doesn't say anything about its elements (required them packaged as a jar)
                  - Doesn't say anything about org.gradle.plugin.api-version (required '8.4')

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

**Comment by jonatan-ivanov** [comment]
Are you sure?
```
The consumer was configured to find a library for use during runtime, compatible with Java 13,
```

Check your build scan for the java version.

**Comment by systems1** [comment]
@jonatan-ivanov 
I checked on another laptop with clean java 21 and build worked now 
so it could be my local multiple java versions issue 
thx

**Comment by jonatan-ivanov** [comment]
Try to run `./gradlew --version` to see what Java version Gradle uses, if it's 21, the toolchain should also use that. I use [asdf](https://asdf-vm.com/) as my version manager but [sdkman](https://sdkman.io/) should also work with the toolchain.

I also upgraded Gradle to 8.5 (latest right now), maybe it helps.
