### ISSUE TITLE
build issue using Java 21[error at \teahouse-main\build.gradle' line: 49]

### ISSUE THREAD

**Issue by rahulchavan888** [jonatan-ivanov/teahouse#11]
Getting below Error While Build 

PS C:\Users\Lenovo\Documents\teahouse-main> ./gradlew bootRun --scan

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\Lenovo\Documents\teahouse-main\build.gradle' line: 49

* What went wrong:
A problem occurred evaluating root project 'teahouse'.
> Cannot invoke method head() on null object

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Get more help at https://help.gradle.org.

BUILD FAILED in 14s

Publishing a build scan to scans.gradle.com requires accepting the Gradle Terms of Service defined at https://gradle.com/terms-of-service. Do you accept these terms? [yes, no] yes

Gradle Terms of Service accepted.

Publishing build scan...
https://gradle.com/s/laevgvpgh3n6y

**Below is the Java version capture used by Gradle:**
> ./gradlew --version
![image](https://github.com/jonatan-ivanov/teahouse/assets/26784568/00c23b07-6e96-48c3-95b5-293d2046b9aa)

I tried redownloading dependencies but not working 
> ./gradlew build --refresh-dependencies
> ./gradlew --refresh-dependencies

**Comment by jonatan-ivanov** [comment]
The project must be in a git repo.
I suggest you to proper clone the project, not download the zip and extract.
